### ISSUE TITLE
a systemd-udevd crash in udev_monitor_receive_device()

### ISSUE THREAD

**Issue by wangyugui** [redhat-plumbers/systemd-rhel8#162]
a systemd-udevd crash in udev_monitor_receive_device()

version:systemd-239-41.el8_3.1.x86_64

```
#gdb /usr/lib/systemd/systemd-udevd /var/lib/systemd/coredump/core.systemd-udevd.0.0d9072fbe44241cb98b5c3bf8185ce26.1144.1615470074000000
(gdb) where
#0  0x00007fa943b79785 in recvmsg () from /lib64/libpthread.so.0
#1  0x00007fa94466f6b9 in udev_monitor_receive_device () from /usr/lib/systemd/libsystemd-shared-239.so
#2  0x00005595b3e17c91 in on_uevent ()
#3  0x00005595b3e18afc in on_inotify ()
#4  0x00007fa944773b40 in source_dispatch () from /usr/lib/systemd/libsystemd-shared-239.so
#5  0x00007fa9447758a5 in sd_event_dispatch () from /usr/lib/systemd/libsystemd-shared-239.so
#6  0x00007fa944775a30 in sd_event_run () from /usr/lib/systemd/libsystemd-shared-239.so
#7  0x00007fa944775c53 in sd_event_loop () from /usr/lib/systemd/libsystemd-shared-239.so
#8  0x00005595b3e14f0c in main ()
(gdb)
```

**Comment by jamacku** [comment]
If it still occurs, please report this issue using our [tracking system](https://github.com/redhat-plumbers/systemd-rhel8/blob/main/CONTRIBUTING.md#filing-issues). We don't support GitHub Issues.
